version: "2.0"
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    container_name: vinyl-disc-crud  
    depends_on: 
      - db
    links:
      - db
    expose:
      - 5000

  db:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: 'crud_db'
      MYSQL_PASSWORD: ''
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: rootpassword